ImageGallery/ImageGallery/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('albums/', include('albums.urls')),
    path('images/', include('images.urls')),
]

ImageGallery/albums/urls.py
from django.urls import path

from albums.views import create
from albums.views import AlbumListView, AlbumDetailView


app_name = 'albums'

urlpatterns = [
    path('', AlbumListView.as_view(), name='index'),
    path('create/', create, name='create'),
    path('<int:pk>/detail', AlbumDetailView.as_view(), name='detail'),
]

ImageGallery/albums/models.py
from django.db import models
from django.db.models import Sum

from aws import create_folder


class AlbumManager(models.Manager):

    def create_by_aws(self, title, description):
        key = create_folder(directory_name=title)
        if key:
            return self.create(
                title=title, 
                description=description,
                key=key)


class Album(models.Model):
    title = models.CharField(max_length=50, null=False, blank=False)
    description = models.TextField()
    # bucket = models.CharField(max_length=100, null=False, blank=False)
    key = models.CharField(max_length=50, null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = AlbumManager()

    def __str__(self):
        return self.title

    @property
    def images(self):
        return self.image_set.all()
    
    @property
    def size(self):
        if self.images:
            return self.images.aggregate(Sum('size'))['size__sum']
        return 0

ImageGallery/albums/forms.py
from django.forms import ModelForm

from albums.models import Album


class AlbumForm(ModelForm):
    class Meta:
        model = Album
        fields = ['title', 'description']

    def __init__(self, *args, **kwargs):
        super(AlbumForm, self).__init__(*args, **kwargs)

        self.fields['title'].widget.attrs.update({
            'class': 'form-control',
            'id': 'title',
            'placeholder': 'Title',
        })

        self.fields['description'].widget.attrs.update({
            'class': 'form-control',
            'id': 'description',
            'placeholder': 'Description',
        })

ImageGallery/albums/views.py
from typing import Any, Dict
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.conf import settings

from albums.forms import AlbumForm
from albums.models import Album

from images.forms import UploadFileForm


class AlbumListView(ListView):
    model = Album
    template_name = 'albums/list.html'
    paginate_by = 10

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['title'] = 'Gallery'
        context['form'] = AlbumForm()

        return context


def create(request):
    form = AlbumForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():

        album = Album.objects.create_by_aws(
            title=form.cleaned_data['title'],
            description=form.cleaned_data['description'])

        return redirect('albums:index')
    

class AlbumDetailView(DetailView):
    model = Album
    template_name = 'albums/detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['title'] = self.get_object().title
        context['form'] = UploadFileForm({
            'album_id': self.get_object().pk
        })
        context['images'] = self.get_object().images
        context['aws'] = {
            'bucket_name': getattr(settings, 'AWS_S3_BUCKET_NAME', None),
            'root_key': getattr(settings, 'AWS_ROOT_FOLDER', '')
        }

        return context

ImageGallery/albums/templates/albums/snippets/modal.html
<div
class="modal fade"
id="album-modal"
tabindex="-1"
aria-labelledby="album-modal-Label"
aria-hidden="true"
>
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="album-modal-Label">New Album</h1>
                <button
                type="button"
                class="btn-close"
                data-bs-dismiss="modal"
                aria-label="Close"
                ></button>
            </div>
            <form action="{% url 'albums:create' %}" method="POST">
                {% csrf_token %}
                <div class="modal-body">
                    {% for field in form %}
                        <div class="form-group mb-3">{{ field }}</div>
                    {% endfor %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">
                    Close
                    </button>
                    <input type="submit" class="btn btn-outline-primary" value="Create" />
                </div>
            </form>
        </div>
    </div>
</div>