ImageGallery/ImageGallery/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('albums/', include('albums.urls')),
    path('images/', include('images.urls')),
]

ImageGallery/albums/urls.py
from django.urls import path

from albums.views import create
from albums.views import AlbumListView, AlbumDetailView


app_name = 'albums'

urlpatterns = [
    path('', AlbumListView.as_view(), name='index'),
    path('create/', create, name='create'),
    path('<int:pk>/detail', AlbumDetailView.as_view(), name='detail'),
]

ImageGallery/images/urls.py
from django.urls import path

from images.views import create, update, show, delete, download, delete_many, download_many, search


app_name = 'images'

urlpatterns = [
    path('create/', create, name='create'),
    path('update/<int:pk>/', update, name='update'),
    path('show/<int:pk>/', show, name='show'),
    path('search', search, name='search'),
    path('delete/<int:pk>/', delete, name='delete'),
    path('delete/many/', delete_many, name='delete_many'),
    path('download/<int:pk>/', download, name='download'),
    path('download/many/', download_many, name='download_many'),
]

ImageGallery/images/models.py
from django.db import models
from django.conf import settings

from aws import rename_file, delete_file

from albums.models import Album


class ImageManager(models.Manager):

    def delete_by_aws(self, id):
        image = self.filter(pk=id).first()
        
        if image and delete_file(image.key):
            image.delete()
            return id


class Image(models.Model):
    key = models.CharField(max_length=100, null=False, blank=False)
    name = models.CharField(max_length=50, null=False, blank=False)
    content_type = models.CharField(max_length=20, null=False, blank=False)
    size = models.IntegerField()
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = ImageManager()

    def __str__(self) -> str:
        return self.name

    @property
    def url(self) -> str:
        bucket_name = getattr(settings, 'AWS_S3_BUCKET_NAME', None)
        root_key = getattr(settings, 'AWS_ROOT_FOLDER', '')
        return f'https://{bucket_name}.s3.amazonaws.com/{root_key + self.key}'

    @property
    def title(self) -> str:
        return self.name.split('.')[0]
    
    @property
    def extension(self) -> str:
        return self.name.split('.')[-1]
    
    def set_name(self, new_name: str) -> None:
        new_name += '.' + self.extension
        new_key = self.album.key + new_name

        if rename_file(self.key, new_key):
            self.key = new_key
            self.name = new_name
            self.save()

ImageGallery/images/forms.py
from django.forms import (
    Form, FileField, FileInput, CharField,
    HiddenInput
)


class UploadFileForm(Form):
    album_id = CharField(required=True, widget=HiddenInput())
    file = FileField(
        required=True,
        label='Imagen',
        widget=FileInput(
            attrs={'accept': 'image/*'}
        )
    )

    def __init__(self, *args, **kwargs):
        super(UploadFileForm, self).__init__(*args, **kwargs)

        self.fields['file'].widget.attrs['class'] = 'form-control-file'

ImageGallery/images/views.py
import json
import shutil

from wsgiref.util import FileWrapper

from pathlib import Path

from django.shortcuts import redirect, get_object_or_404
from django.http import JsonResponse, HttpResponse
from django.urls import reverse
from django.template.loader import get_template
from django.views.decorators.csrf import csrf_exempt

from aws import upload_image, get_file_content, download_file

from albums.models import Album

from images.forms import UploadFileForm
from images.models import Image


@csrf_exempt
def search(request):
    if request.method == 'GET' and request.GET.get('q'):

        template = get_template('images/snippets/image.html')

        images = [
            template.render({'image': image})
            for image in Image.objects.filter(name__startswith=request.GET.get('q'))
        ]

        return JsonResponse({
            'success': True,
            'images': images
        })


def show(request, pk):
    image = get_object_or_404(Image, pk=pk)
    return JsonResponse({
        'id': image.pk,
        'name': image.name,
        'delete_url': reverse('images:delete', kwargs={'pk': image.pk})
    })


def update(request, pk):
    
    if request.method == 'POST':
        image = get_object_or_404(Image, pk=pk)
        new_name = request.POST.get('name', '')
        image.set_name(new_name)

        return JsonResponse({
            'id': image.id,
            'name': image.title,
            'url': image.url
        })
    
    return JsonResponse({
        'id': None,
        'name': None,
        'url': None
    })
    

def create(request):

    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            file = form.cleaned_data['file']
            album = get_object_or_404(Album, pk=form.cleaned_data['album_id'])

            file_name = file._name.lower().replace(' ', '_')
            key = album.key + file_name
            
            if upload_image(key, file):

                image = Image.objects.create(
                    name=file_name,
                    content_type=file.content_type,
                    size=file.size,
                    key=key,
                    album=album
                )

            return redirect('albums:detail', album.pk)
        else:
            print(form.errors)

    else:
        print('METHOD NOT VALID')


def delete(request, pk):
    image = get_object_or_404(Image, pk=pk)
    album = image.album

    image.objects.delete_by_aws(image.pk)

    return redirect('albums:detail', album.id)


@csrf_exempt
def delete_many(request):
    if request.method == 'POST':
        payload = json.loads(request.body)
        ids = payload.get('ids', [])

        return JsonResponse({
            'ids': [ Image.objects.delete_by_aws(id) for id in ids ]
        })


def download(request, pk):
    image = get_object_or_404(Image, pk=pk)
    content = get_file_content(image.key)
    if content:
        response = HttpResponse(content, content_type=image.content_type)
        response['Content-Disposition'] = f'attachment; filename={image.name}'
        return response
    print('ERROR: an error with aws s3')
    return redirect('albums:detail', image.album.id)


def download_many(request):

    dir_path = 'tmp/images/'
    Path(dir_path).mkdir(parents=True, exist_ok=True)  # Crea la carpeta si no existe

    for id in request.GET.get('ids', '').split(','):
        image = Image.objects.filter(pk=int(id)).first()
        if image:
            local_path = dir_path + image.name
            download_file(image.key, local_path)

    shutil.make_archive('tmp/images', 'zip', dir_path)

    # Eliminar la carpeta images?

    wrapper = FileWrapper(open('tmp/images.zip', 'rb'))

    response = HttpResponse(wrapper, content_type='application/zip')
    response['Content-Disposition'] = 'attachment; filename="images.zip"'
    return response

ImageGallery/images/templates/images/snippets/image.html
<tr class="row-image" image-id="{{ image.pk }}" id="tr_image_{{ image.pk }}">
    <td>
        <div class="form-check">
            <input type="checkbox" class="form-check-input chk-image" image-id="{{ image.pk }}">
        </div>
    </td>
    <td>
        <input type="hidden" value="{{ image.url }}" id="image_preview_{{ image.pk }}">
        <div id="image_name_{{ image.pk }}">
            {{ image.title }}
        </div>
        <form action="{% url 'images:update' image.pk %}" method="post" class="image-form" image-id="{{ image.pk }}">
            {% csrf_token %}
            <input type="hidden" value="{{ image.title }}" class="form-control" id="image_input_name_{{ image.pk }}" name="name">
        </form>
    </td>
    <td>{{ image.created_at }}</td>
    <td>{{ image.size }}</td>
    <td>
        <div class="dropdown">
            <button type="button" class="btn btn-outline-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                ...
            </button>
            <div class="dropdown-menu">
                <a href="{{ image.url }}" target="_blank" class="dropdown-item">Preview</a>
                <a href="" class="dropdown-item image-edit" image-id="{{ image.pk }}">Edit name</a>
                <a href="{% url 'images:download' image.pk %}" class="dropdown-item">Download</a>
                <div class="dropdown-divider"></div>
                <a href="{% url 'images:show' image.pk %}" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#image_delete_modal">Delete</a>
            </div>
        </div>
    </td>
</tr>

ImageGallery/images/templates/images/snippets/modal.html
<div
class="modal fade"
id="image-modal"
tabindex="-1"
aria-labelledby="image-modal-Label"
aria-hidden="true"
>
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="image-modal-Label">New Image</h1>
                <button
                type="button"
                class="btn-close"
                data-bs-dismiss="modal"
                aria-label="Close"
                ></button>
            </div>
            <form action="{% url 'images:create' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="modal-body">
                    {% for field in form %}
                        <div class="form-group mb-3">{{ field }}</div>
                    {% endfor %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">
                    Close
                    </button>
                    <input type="submit" class="btn btn-outline-primary" value="Upload" />
                </div>
            </form>
        </div>
    </div>
</div>

ImageGallery/images/templates/images/snippets/modal_delete.html
<div
class="modal fade"
id="image_delete_modal"
tabindex="-1"
>
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="image_modal_Label">Delete Image</h1>
                <button
                type="button"
                class="btn-close"
                data-bs-dismiss="modal"
                aria-label="Close"
                ></button>
            </div>
                <div class="modal-body">
                    Do you want to delete the image <strong id="strong_name"></strong>?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
                    <a href="" id="btn_delete" class="btn btn-outline-danger">Delete</a>
                </div>
        </div>
    </div>
</div>