ImageGallery/ImageGallery/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('albums/', include('albums.urls')),
    path('images/', include('images.urls')),
]

ImageGallery/albums/urls.py
from django.urls import path

from albums.views import create
from albums.views import AlbumListView, AlbumDetailView


app_name = 'albums'

urlpatterns = [
    path('', AlbumListView.as_view(), name='index'),
    path('create/', create, name='create'),
    path('<int:pk>/detail', AlbumDetailView.as_view(), name='detail'),
]

ImageGallery/images/urls.py
from django.urls import path

from images.views import create, update, show, delete, download, delete_many, download_many, search


app_name = 'images'

urlpatterns = [
    path('create/', create, name='create'),
    path('update/<int:pk>/', update, name='update'),
    path('show/<int:pk>/', show, name='show'),
    path('search', search, name='search'),
    path('delete/<int:pk>/', delete, name='delete'),
    path('delete/many/', delete_many, name='delete_many'),
    path('download/<int:pk>/', download, name='download'),
    path('download/many/', download_many, name='download_many'),
]

ImageGallery/albums/models.py
from django.db import models
from django.db.models import Sum

from aws import create_folder


class AlbumManager(models.Manager):

    def create_by_aws(self, title, description):
        key = create_folder(directory_name=title)
        if key:
            return self.create(
                title=title, 
                description=description,
                key=key)


class Album(models.Model):
    title = models.CharField(max_length=50, null=False, blank=False)
    description = models.TextField()
    # bucket = models.CharField(max_length=100, null=False, blank=False)
    key = models.CharField(max_length=50, null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = AlbumManager()

    def __str__(self):
        return self.title

    @property
    def images(self):
        return self.image_set.all()
    
    @property
    def size(self):
        if self.images:
            return self.images.aggregate(Sum('size'))['size__sum']
        return 0

ImageGallery/albums/forms.py
from django.forms import ModelForm

from albums.models import Album


class AlbumForm(ModelForm):
    class Meta:
        model = Album
        fields = ['title', 'description']

    def __init__(self, *args, **kwargs):
        super(AlbumForm, self).__init__(*args, **kwargs)

        self.fields['title'].widget.attrs.update({
            'class': 'form-control',
            'id': 'title',
            'placeholder': 'Title',
        })

        self.fields['description'].widget.attrs.update({
            'class': 'form-control',
            'id': 'description',
            'placeholder': 'Description',
        })

ImageGallery/albums/views.py
from typing import Any, Dict
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.conf import settings

from albums.forms import AlbumForm
from albums.models import Album

from images.forms import UploadFileForm


class AlbumListView(ListView):
    model = Album
    template_name = 'albums/list.html'
    paginate_by = 10

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['title'] = 'Gallery'
        context['form'] = AlbumForm()

        return context


def create(request):
    form = AlbumForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():

        album = Album.objects.create_by_aws(
            title=form.cleaned_data['title'],
            description=form.cleaned_data['description'])

        return redirect('albums:index')
    

class AlbumDetailView(DetailView):
    model = Album
    template_name = 'albums/detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['title'] = self.get_object().title
        context['form'] = UploadFileForm({
            'album_id': self.get_object().pk
        })
        context['images'] = self.get_object().images
        context['aws'] = {
            'bucket_name': getattr(settings, 'AWS_S3_BUCKET_NAME', None),
            'root_key': getattr(settings, 'AWS_ROOT_FOLDER', '')
        }

        return context

ImageGallery/albums/templates/albums/detail.html
{% extends 'base/base.html' %}

{% block style %}
    <style>
        .row-image {
            cursor: pointer;
        }
    </style>
{% endblock %}

{% block content %}

    {% include 'images/snippets/modal.html' %}
    {% include 'images/snippets/modal_delete.html' %}

    <div class="row mt-4 mb-4">
        <div class="col-6">
            <h1>Album Detail</h1>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <h2><a href="{% url 'albums:index' %}">Gallery</a> | {{ title }}</h2>
        </div>
    </div>

    <div class="row mt-2">
        <div class="col">
            <form action="{% url 'images:search' %}" id="searchImage">
                <input type="text" class="form-control" name="q" placeholder="Search..." />
            </form>
        </div>
    </div>

    <hr>

    <div class="row mt-4">
        <div class="col">
            <button
                type="button"
                class="btn btn-outline-primary"
                data-bs-toggle="modal"
                data-bs-target="#image-modal">
                New Image
            </button>
            <a
                href="{% url 'images:download_many' %}"
                id="btnDownload"
                class="btn btn-outline-info disabled">
                Download
            </a>
            <a
                href="{% url 'images:delete_many' %}"
                id="btnDelete"
                class="btn btn-outline-danger disabled">
                Delete
            </a>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-8">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" id="chk_all_images">
                            </div>
                        </th>
                        <th>Name</th>
                        <th>Create date</th>
                        <th>Size</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody id="tableImages">
                    {% for image in images %}
                       {% include 'images/snippets/image.html' %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-4">
            <img src="" alt="" width="300" id="image_preview">
        </div>
    </div>

{% endblock %}

{% block javascript %}
    <script>
        const imagepreview = document.getElementById("image_preview");
        const imageDefaultUrl = "https://{{ aws.bucket_name }}.s3.amazonaws.com/{{ aws.root_key }}default.png";
        const chk_all_images = document.getElementById('chk_all_images');
        const btnDownload = document.getElementById('btnDownload');
        const btnDelete = document.getElementById('btnDelete');
        const searchImage = document.getElementById('searchImage');
        const myModalEl = document.getElementById('image_delete_modal');

        function checkInputs(){
            let images = document.querySelectorAll('input.chk-image[type="checkbox"]:checked');
            if (images.length > 1){
                btnDownload.classList.remove('disabled');
                btnDelete.classList.remove('disabled');
            } else {
                btnDownload.classList.add('disabled');
                btnDelete.classList.add('disabled');
            }
        }

        function selectRow(row) {
            let imageId = row.getAttribute('image-id');
            let input = document.getElementById('image_preview_' + imageId);
            imagepreview.src = input.value;

            document.querySelectorAll('table-active').forEach(element => {
                element.classList.remove('table-active');
            });
            row.classList.add('table-active');
        }

        function setDefaultImage() {
            let rows = document.getElementsByTagName('tr');
            if (rows.length >= 2) {
                selectRow(rows[1]);
            } else {
                imagepreview.src = imageDefaultUrl;
            }
        }

        function getImagesSelected() {
            let ids = [];
            let images = document.querySelectorAll('input.chk-image[type="checkbox"]:checked');

            for (let i = 0; i < images.length; i++) {
                const imageId = images[i].getAttribute('image-id');
                ids.push(imageId);
            }

            return ids;
        }

        function registerEvents() {
            document.querySelectorAll('.row-image').forEach(element => {
                element.addEventListener('click', function(event) {
                    selectRow(this);
                });
            });

            document.querySelectorAll('.image-edit').forEach(element => {
                element.addEventListener('click', function(event) {
                    event.preventDefault();
                    const imageId = this.getAttribute('image-id');
                    const input = document.getElementById('image_input_name_' + imageId);
                    const div = document.getElementById('image_name_' + imageId);
                    input.setAttribute('type', 'text');
                    div.style.display = 'none';
                });
            });

            document.querySelectorAll('.image-form').forEach(element => {
                element.addEventListener('submit', function(event) {
                    event.preventDefault();

                    fetch(this.action, {
                        body: new FormData(this),
                        method: 'POST'
                    })
                    .then(response => response.json())
                    .then(data => {
                        const imageId = this.getAttribute('image-id');
                        const input = document.getElementById('image_input_name_' + imageId);
                        const div = document.getElementById('image_name_' + imageId);
                        const inputPreview = document.getElementById('image_preview_' + imageId);
                        input.value = data.name;
                        input.setAttribute('type', 'hidden');
                        div.innerHTML = data.name;
                        div.style.display = 'block';
                        inputPreview.value = data.url;
                    })
                })
            });

            document.querySelectorAll('input.chk-image').forEach(element => {
                element.addEventListener('change', function(event){
                    checkInputs();
                });
            });
        }


        myModalEl.addEventListener('show.bs.modal', event => {
            let item = event.relatedTarget;

            fetch(item.href)
            .then(response => response.json())
            .then(function(data) {
                myModalEl.querySelector('#strong_name').textContent = data.name;
                myModalEl.querySelector('#btn_delete').href = data.delete_url;
            });
        });

        chk_all_images.addEventListener('change', function(event) {
            document.querySelectorAll('.chk-image').forEach(element => {
                element.checked = this.checked;
            });
            checkInputs();
        });

        btnDelete.addEventListener('click', function(event) {
            event.preventDefault();
            
            let ids = getImagesSelected();

            fetch(this.href, {
                method: 'POST',
                body: JSON.stringify({
                    'ids': ids
                })
            })
            .then(response => response.json())
            .then(function(data){
                for (let i = 0; i < data.ids.length; i++) {
                    const imageId = data.ids[i];
                    document.getElementById("tr_image_" + imageId).remove();
                }
                setDefaultImage();
            });
        });

        btnDownload.addEventListener('click', function(event) {
            event.preventDefault();

            console.log('DESCARGAR');

            let ids = getImagesSelected();

            console.log(ids);

            window.location.href = this.href + '?ids=' + ids;

        });

        searchImage.addEventListener('submit', function(event) {
            event.preventDefault();
            
            fetch(this.action + '?q=' + this.q.value)
            .then(response => response.json())
            .then(data => {
                let table = document.getElementById('tableImages');
                table.innerHTML = data.images.toString().replaceAll(',', '');

                registerEvents();
                setDefaultImage();
            });
        });

        registerEvents();
        setDefaultImage();
    </script>
{% endblock %}

ImageGallery/albums/templates/albums/list.html
{% extends 'base/base.html' %}

{% block content %}

    {% include 'albums/snippets/modal.html' %}

    <div class="row mt-4 mb-4">

        <div class="col-6">
            <h1>Gallery</h1>
        </div>

        <div class="col-6 text-end">
            <button
                type="button"
                class="btn btn-outline-primary"
                data-bs-toggle="modal"
                data-bs-target="#album-modal">
                New Album
            </button>
        </div>

    </div>


    <div class="row">
        <div class="col">
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Title</th>
                    <th scope="col">Create Date</th>
                    <th scope="col">Items</th>
                    <th scope="col">Size</th>
                  </tr>
                </thead>
                <tbody>
                    {% for album in object_list %}
                        <tr>
                            <th>
                                <a href="{% url 'albums:detail' album.pk %}">
                                    <i class="fas fa-folder"></i> {{ album.title }}
                                </a>
                            </th>
                            <td>{{ album.created_at | date:'d M Y' }}</td>
                            <td>{{ album.images.count }}</td>
                            <td>{{ album.size }} bytes</td>
                        </tr>
                    {% endfor %}
                </tbody>
              </table>
        </div>
    </div>

{% endblock %}